import JSZip from 'jszip';

export function generateBotZip(
  token: string = '',
  clientId: string = '1368350667634376785',
  clientSecret: string = '-c7yfLwX-ZojIhLF3TCHZxavvmLyCN9K',
  dashboardUrl: string = 'https://ais-dev-5cjov5lzkdkahvqz3a7yun-454494415153.europe-west2.run.app'
) {
  const zip = new JSZip();

  // 1. package.json
  const packageJson = {
    name: "kitek-bot",
    version: "5.0.0",
    description: "KitekBot Discord Bot v5.0.0 — potężny moduł powitań w stylu message.style, Discord.js v14 oraz REST API",
    main: "index.js",
    scripts: {
      prestart: "npm install --no-audit --prefer-offline",
      start: "node index.js",
      dev: "nodemon index.js"
    },
    dependencies: {
      "discord.js": "^14.16.3",
      "dotenv": "^16.4.5",
      "express": "^4.21.2",
      "cors": "^2.8.5"
    },
    devDependencies: {
      "nodemon": "^3.1.7"
    },
    keywords: ["discord", "bot", "kitekbot", "welcome-system", "message-style", "v5.0.0"],
    author: "KitekBot Team",
    license: "ISC"
  };
  zip.file("package.json", JSON.stringify(packageJson, null, 2));

  // 2. .env
  const cleanInitialToken = token.replace(/["']/g, '').trim();
  const envContent = [
    '# Discord Bot Token (wklej swój token bota z Discord Developer Portal -> Bot -> Reset Token)',
    'DISCORD_TOKEN=' + (cleanInitialToken || 'TWOJ_DISCORD_BOT_TOKEN_TUTAJ'),
    '',
    '# Discord Application Credentials',
    'DISCORD_CLIENT_ID=' + clientId,
    'DISCORD_CLIENT_SECRET=' + clientSecret,
    '',
    '# Adres URL Dashboardu (do natychmiastowej synchronizacji statusu serwerów)',
    'DASHBOARD_URL=' + (dashboardUrl || 'https://ais-dev-5cjov5lzkdkahvqz3a7yun-454494415153.europe-west2.run.app'),
    '',
    '# Port dla REST / HTTPS API bota (domyślnie 3001, na Pterodactylu zmienna PORT przypisywana automatycznie)',
    'PORT=3001',
    '',
    '# Opcjonalny klucz bezpieczeństwa dla REST API bota (zostaw puste lub wymyśl własne hasło np. mojehaslo123)',
    'BOT_API_SECRET=',
    '',
    '# Opcjonalny publiczny adres URL REST API bota (np. http://ADRES_IP_TWOJEGO_SERWERA:3001)',
    'PUBLIC_BOT_API_URL=',
    ''
  ].join('\n');
  zip.file(".env", envContent);

  // 3. .env.example
  const envExampleContent = [
    '# Wzór pliku konfiguracyjnego bota v5.0.0',
    'DISCORD_TOKEN=TWOJ_DISCORD_BOT_TOKEN_TUTAJ',
    'DISCORD_CLIENT_ID=' + clientId,
    'DISCORD_CLIENT_SECRET=' + clientSecret,
    'DASHBOARD_URL=' + (dashboardUrl || 'https://ais-dev-5cjov5lzkdkahvqz3a7yun-454494415153.europe-west2.run.app'),
    'PORT=3001',
    'BOT_API_SECRET=',
    'PUBLIC_BOT_API_URL=',
    ''
  ].join('\n');
  zip.file(".env.example", envExampleContent);

  // 4. utils/configManager.js
  const configManagerJs = [
    "const fs = require('fs');",
    "const path = require('path');",
    "",
    "const SERWERY_DIR = path.join(process.cwd(), 'Serwery');",
    "",
    "if (!fs.existsSync(SERWERY_DIR)) {",
    "  try { fs.mkdirSync(SERWERY_DIR, { recursive: true }); } catch (e) {}",
    "}",
    "",
    "function getDefaultWelcomeConfig() {",
    "  return {",
    "    enabled: true,",
    "    channelId: null,",
    "    message: 'Hej {user}, witamy w naszych progach! 🌟 Rozgość się i zapoznaj z regulaminem.',",
    "    useEmbed: true,",
    "    embed: {",
    "      color: '#5865F2',",
    "      authorName: 'Oficjalny Serwer KitekBot',",
    "      authorIcon: 'https://cdn.discordapp.com/embed/avatars/0.png',",
    "      authorUrl: '',",
    "      title: '👋 Witamy nowego użytkownika!',",
    "      titleUrl: '',",
    "      description: 'Cieszymy się, że jesteś z nami, **{user}**! Jesteś naszym **{memberCount}** członkiem na serwerze **{server.name}**!\\n\\nPamiętaj, aby zachowywać kulturę i sprawdzić poniższe kanały:',",
    "      fields: [",
    "        {",
    "          id: 'f-1',",
    "          name: '📜 Regulamin',",
    "          value: 'Sprawdź najważniejsze zasady panujące na serwerze.',",
    "          inline: true",
    "        },",
    "        {",
    "          id: 'f-2',",
    "          name: '💬 Dyskusje',",
    "          value: 'Dołącz do rozmów na kanale głównym!',",
    "          inline: true",
    "        }",
    "      ],",
    "      thumbnailUrl: '',",
    "      imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',",
    "      footerText: 'KitekBot Welcome System • Życzymy miłej zabawy!',",
    "      footerIcon: 'https://cdn.discordapp.com/embed/avatars/0.png',",
    "      includeTimestamp: true",
    "    },",
    "    buttons: [",
    "      {",
    "        id: 'btn-1',",
    "        label: 'Odwiedź stronę bota',",
    "        style: 'LINK',",
    "        url: 'https://kitekbot.vercel.app',",
    "        emoji: '🌐'",
    "      },",
    "      {",
    "        id: 'btn-2',",
    "        label: 'Zweryfikuj konto',",
    "        style: 'SUCCESS',",
    "        customId: 'verify_welcome_btn',",
    "        emoji: '✅'",
    "      }",
    "    ]",
    "  };",
    "}",
    "",
    "function getDefaultConfig(guildId, guildName = '') {",
    "  return {",
    "    guildId: String(guildId),",
    "    guildName: guildName || ('Serwer ' + guildId),",
    "    prefix: '!',",
    "    language: 'pl',",
    "    welcome: getDefaultWelcomeConfig(),",
    "    embedColor: '#5865F2',",
    "    updatedAt: new Date().toISOString()",
    "  };",
    "}",
    "",
    "function getGuildConfig(guildId, guildName = '') {",
    "  const filePath = path.join(SERWERY_DIR, guildId + '.json');",
    "  const defaultConf = getDefaultConfig(guildId, guildName);",
    "  if (fs.existsSync(filePath)) {",
    "    try {",
    "      const data = fs.readFileSync(filePath, 'utf8');",
    "      const parsed = JSON.parse(data);",
    "      const mergedWelcome = Object.assign({}, defaultConf.welcome, parsed.welcome || {});",
    "      if (parsed.welcome && parsed.welcome.embed) {",
    "        mergedWelcome.embed = Object.assign({}, defaultConf.welcome.embed, parsed.welcome.embed);",
    "        if (Array.isArray(parsed.welcome.embed.fields)) {",
    "          mergedWelcome.embed.fields = parsed.welcome.embed.fields;",
    "        }",
    "      }",
    "      if (parsed.welcome && Array.isArray(parsed.welcome.buttons)) {",
    "        mergedWelcome.buttons = parsed.welcome.buttons;",
    "      }",
    "      return Object.assign({}, defaultConf, parsed, { guildId: String(guildId), welcome: mergedWelcome });",
    "    } catch (err) {",
    "      console.error('[BŁĄD] Nie można odczytać pliku ' + guildId + '.json:', err.message);",
    "    }",
    "  }",
    "  saveGuildConfig(guildId, defaultConf);",
    "  return defaultConf;",
    "}",
    "",
    "function saveGuildConfig(guildId, newConfig) {",
    "  const filePath = path.join(SERWERY_DIR, guildId + '.json');",
    "  let current = {};",
    "  if (fs.existsSync(filePath)) {",
    "    try {",
    "      current = JSON.parse(fs.readFileSync(filePath, 'utf8'));",
    "    } catch (e) {}",
    "  } else {",
    "    current = getDefaultConfig(guildId);",
    "  }",
    "  const merged = Object.assign({}, current, newConfig, {",
    "    guildId: String(guildId),",
    "    updatedAt: new Date().toISOString()",
    "  });",
    "  try {",
    "    fs.writeFileSync(filePath, JSON.stringify(merged, null, 2), 'utf8');",
    "    console.log('💾 [Zapis JSON] Pomyślnie zaktualizowano plik Serwery/' + guildId + '.json');",
    "    return merged;",
    "  } catch (err) {",
    "    return merged;",
    "  }",
    "}",
    "",
    "function getAllConfigs() {",
    "  if (!fs.existsSync(SERWERY_DIR)) return [];",
    "  try {",
    "    const files = fs.readdirSync(SERWERY_DIR).filter(f => f.endsWith('.json') && f !== 'active_bot_guilds.json');",
    "    return files.map(file => {",
    "      try {",
    "        const content = fs.readFileSync(path.join(SERWERY_DIR, file), 'utf8');",
    "        return JSON.parse(content);",
    "      } catch (e) {",
    "        return null;",
    "      }",
    "    }).filter(Boolean);",
    "  } catch (e) {",
    "    return [];",
    "  }",
    "}",
    "",
    "module.exports = {",
    "  getDefaultConfig,",
    "  getDefaultWelcomeConfig,",
    "  getGuildConfig,",
    "  saveGuildConfig,",
    "  getAllConfigs,",
    "  SERWERY_DIR",
    "};"
  ].join('\n');
  zip.file("utils/configManager.js", configManagerJs);

  // 5. index.js
  const indexJs = [
    "/**",
    " * 🤖 KitekBot - Discord Bot & REST API v5.0.0",
    " * Profesjonalny moduł powitań w stylu message.style oraz synchronizacja w czasie rzeczywistym z panelem Web.",
    " */",
    "",
    "const fs = require('fs');",
    "const path = require('path');",
    "const { execSync } = require('child_process');",
    "",
    "// Sprawdzenie i automatyczna instalacja brakujących zależności npm",
    "if (!fs.existsSync(path.join(__dirname, 'node_modules', 'discord.js'))) {",
    "  console.log('📦 Trwa automatyczna instalacja brakujących pakietów npm...');",
    "  try {",
    "    execSync('npm install --no-audit --prefer-offline', { stdio: 'inherit' });",
    "    console.log('✅ Wszystkie pakiety zostały pomyślnie zainstalowane!');",
    "  } catch (err) {",
    "    console.error('⚠️ Błąd podczas automatycznej instalacji:', err.message);",
    "  }",
    "}",
    "",
    "require('dotenv').config();",
    "const {",
    "  Client,",
    "  GatewayIntentBits,",
    "  EmbedBuilder,",
    "  ActionRowBuilder,",
    "  ButtonBuilder,",
    "  ButtonStyle,",
    "  ActivityType,",
    "  REST,",
    "  Routes,",
    "  SlashCommandBuilder",
    "} = require('discord.js');",
    "const express = require('express');",
    "const cors = require('cors');",
    "const { getGuildConfig, saveGuildConfig, getAllConfigs } = require('./utils/configManager');",
    "",
    "// --- 1. INICJALIZACJA BOTA DISCORD ---",
    "const client = new Client({",
    "  intents: [",
    "    GatewayIntentBits.Guilds,",
    "    GatewayIntentBits.GuildMessages,",
    "    GatewayIntentBits.MessageContent,",
    "    GatewayIntentBits.GuildMembers",
    "  ]",
    "});",
    "",
    "// Funkcja budująca kompletną wiadomość powitalną (treść, embed, pola, przyciski) w stylu message.style",
    "function buildWelcomePayload(guild, member, config) {",
    "  const w = (config && config.welcome) || {};",
    "  const userMention = member ? ('<@' + member.id + '>') : '@Użytkownik';",
    "  const userName = (member && member.user) ? member.user.username : 'Użytkownik';",
    "  const userTag = (member && member.user) ? member.user.tag : 'Użytkownik#0000';",
    "  const userAvatar = (member && member.user && typeof member.user.displayAvatarURL === 'function')",
    "    ? member.user.displayAvatarURL({ dynamic: true })",
    "    : 'https://cdn.discordapp.com/embed/avatars/0.png';",
    "  const guildName = guild ? guild.name : 'Serwer';",
    "  const memberCount = guild ? String(guild.memberCount) : '1';",
    "",
    "  const replaceVars = (str) => {",
    "    if (!str || typeof str !== 'string') return '';",
    "    return str",
    "      .replace(/{user\\.mention}/g, userMention)",
    "      .replace(/{user\\.tag}/g, userTag)",
    "      .replace(/{user\\.name}/g, userName)",
    "      .replace(/{user\\.id}/g, member ? String(member.id) : '123456789')",
    "      .replace(/{user\\.avatar}/g, userAvatar)",
    "      .replace(/{user}/g, userMention)",
    "      .replace(/{server\\.name}/g, guildName)",
    "      .replace(/{server}/g, guildName)",
    "      .replace(/{memberCount}/g, memberCount);",
    "  };",
    "",
    "  const payload = {};",
    "  if (w.message && w.message.trim()) {",
    "    payload.content = replaceVars(w.message);",
    "  }",
    "",
    "  if (w.useEmbed && w.embed) {",
    "    const e = w.embed;",
    "    const embed = new EmbedBuilder();",
    "    if (e.color) {",
    "      try { embed.setColor(e.color); } catch (err) { embed.setColor('#5865F2'); }",
    "    }",
    "    if (e.title && e.title.trim()) {",
    "      embed.setTitle(replaceVars(e.title));",
    "      if (e.titleUrl && e.titleUrl.startsWith('http')) embed.setURL(e.titleUrl);",
    "    }",
    "    if (e.description && e.description.trim()) {",
    "      embed.setDescription(replaceVars(e.description));",
    "    }",
    "    if (e.authorName && e.authorName.trim()) {",
    "      embed.setAuthor({",
    "        name: replaceVars(e.authorName),",
    "        iconURL: e.authorIcon && e.authorIcon.startsWith('http') ? e.authorIcon : undefined,",
    "        url: e.authorUrl && e.authorUrl.startsWith('http') ? e.authorUrl : undefined",
    "      });",
    "    }",
    "    if (e.thumbnailUrl && e.thumbnailUrl.startsWith('http')) {",
    "      embed.setThumbnail(e.thumbnailUrl);",
    "    }",
    "    if (e.imageUrl && e.imageUrl.startsWith('http')) {",
    "      embed.setImage(e.imageUrl);",
    "    }",
    "    if (e.footerText && e.footerText.trim()) {",
    "      embed.setFooter({",
    "        text: replaceVars(e.footerText),",
    "        iconURL: e.footerIcon && e.footerIcon.startsWith('http') ? e.footerIcon : undefined",
    "      });",
    "    }",
    "    if (e.includeTimestamp) {",
    "      embed.setTimestamp();",
    "    }",
    "    if (Array.isArray(e.fields) && e.fields.length > 0) {",
    "      for (const f of e.fields) {",
    "        if (f.name && f.value) {",
    "          embed.addFields({",
    "            name: replaceVars(f.name),",
    "            value: replaceVars(f.value),",
    "            inline: Boolean(f.inline)",
    "          });",
    "        }",
    "      }",
    "    }",
    "    payload.embeds = [embed];",
    "  }",
    "",
    "  if (Array.isArray(w.buttons) && w.buttons.length > 0) {",
    "    const row = new ActionRowBuilder();",
    "    for (const b of w.buttons.slice(0, 5)) {",
    "      const btn = new ButtonBuilder();",
    "      if (b.label) btn.setLabel(b.label);",
    "      if (b.emoji) {",
    "        try { btn.setEmoji(b.emoji); } catch (e) {}",
    "      }",
    "      switch (b.style) {",
    "        case 'LINK':",
    "          btn.setStyle(ButtonStyle.Link);",
    "          btn.setURL(b.url && b.url.startsWith('http') ? b.url : 'https://discord.com');",
    "          break;",
    "        case 'SUCCESS':",
    "          btn.setStyle(ButtonStyle.Success);",
    "          btn.setCustomId(b.customId || ('btn_' + b.id));",
    "          break;",
    "        case 'DANGER':",
    "          btn.setStyle(ButtonStyle.Danger);",
    "          btn.setCustomId(b.customId || ('btn_' + b.id));",
    "          break;",
    "        case 'SECONDARY':",
    "          btn.setStyle(ButtonStyle.Secondary);",
    "          btn.setCustomId(b.customId || ('btn_' + b.id));",
    "          break;",
    "        case 'PRIMARY':",
    "        default:",
    "          btn.setStyle(ButtonStyle.Primary);",
    "          btn.setCustomId(b.customId || ('btn_' + b.id));",
    "          break;",
    "      }",
    "      row.addComponents(btn);",
    "    }",
    "    payload.components = [row];",
    "  }",
    "",
    "  return payload;",
    "}",
    "",
    "// Rejestracja komend slash",
    "async function registerSlashCommands(token, clientId) {",
    "  if (!token || !clientId) return;",
    "  try {",
    "    const commands = [",
    "      new SlashCommandBuilder().setName('pomoc').setDescription('Wyświetla pomoc i informacje o KitekBocie'),",
    "      new SlashCommandBuilder().setName('ping').setDescription('Sprawdza opóźnienie bota'),",
    "      new SlashCommandBuilder().setName('stan').setDescription('Pokazuje stan serwera i powitań')",
    "    ].map(cmd => cmd.toJSON());",
    "",
    "    const rest = new REST({ version: '10' }).setToken(token);",
    "    console.log('⚡ Rozpoczęto rejestrację globalnych komend slash (/)...');",
    "    await rest.put(Routes.applicationCommands(clientId), { body: commands });",
    "    console.log('✅ Zarejestrowano pomyślnie komendy slash: /pomoc, /ping, /stan');",
    "  } catch (err) {",
    "    console.error('⚠️ Błąd rejestracji komend slash:', err.message);",
    "  }",
    "}",
    "",
    "let syncCount = 0;",
    "",
    "client.once('ready', async (c) => {",
    "  const botUser = c ? c.user : client.user;",
    "  console.log('\\n=======================================================');",
    "  console.log('✅ KitekBot v5.0.0 jest ONLINE jako: ' + botUser.tag + ' (ID: ' + botUser.id + ')');",
    "  ",
    "  try {",
    "    await client.guilds.fetch();",
    "  } catch (e) {}",
    "",
    "  console.log('🌐 Aktywne serwery bota (' + client.guilds.cache.size + '):');",
    "  client.guilds.cache.forEach(g => {",
    "    console.log('   📌 ' + g.name + ' (ID: ' + g.id + ') - ' + g.memberCount + ' członków');",
    "  });",
    "  console.log('=======================================================\\n');",
    "",
    "  botUser.setActivity('Dashboard v5.0.0 | /pomoc', { type: ActivityType.Playing });",
    "",
    "  const rawToken = (process.env.DISCORD_TOKEN || '').replace(/[\"']/g, '').replace(/^Bot\\s+/i, '').trim();",
    "  const clientId = (process.env.DISCORD_CLIENT_ID || '1368350667634376785').trim();",
    "  if (rawToken && clientId) {",
    "    registerSlashCommands(rawToken, clientId);",
    "  }",
    "",
    "  await syncWithDashboard(true);",
    "  setInterval(() => syncWithDashboard(false), 2000);",
    "});",
    "",
    "// Funkcja synchronizacji serwerów z Dashboardem",
    "async function syncWithDashboard(isInitial = false, options = {}) {",
    "  const dashboardUrl = (process.env.DASHBOARD_URL || '" + dashboardUrl + "').trim();",
    "  try {",
    "    if (!client.isReady()) return;",
    "    const guildIds = client.guilds.cache.map(g => String(g.id));",
    "    const url = dashboardUrl.replace(/\\/$/, '') + '/api/bot/sync';",
    "    syncCount++;",
    "",
    "    const payloadData = {",
    "      guildIds: guildIds,",
    "      replace: options.replace !== undefined ? options.replace : true,",
    "      botTag: client.user ? client.user.tag : 'KitekBot',",
    "      botId: client.user ? client.user.id : null,",
    "      version: '5.0.0',",
    "      botApiUrl: process.env.PUBLIC_BOT_API_URL || null,",
    "      ping: client.ws.ping > 0 ? client.ws.ping : null,",
    "      uptimeSeconds: Math.floor(process.uptime()),",
    "      timestamp: Date.now()",
    "    };",
    "",
    "    if (options.add) payloadData.add = String(options.add);",
    "    if (options.remove) payloadData.remove = String(options.remove);",
    "",
    "    const payload = JSON.stringify(payloadData);",
    "    const res = await fetch(url, {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: payload",
    "    });",
    "",
    "    if (res.ok) {",
    "      if (isInitial || syncCount === 1 || options.add || options.remove) {",
    "        console.log('✅ [Dashboard Sync] Zsynchronizowano pomyślnie z Dashboardem (HTTP ' + res.status + ')!');",
    "      }",
    "    }",
    "  } catch (e) {",
    "    if (isInitial || syncCount % 15 === 0) {",
    "      console.error('❌ [Dashboard Sync] Błąd połączenia z panelem: ' + e.message);",
    "    }",
    "  }",
    "}",
    "",
    "client.on('guildCreate', async (guild) => {",
    "  console.log('🎉 [Event] Bot dodany do serwera: ' + guild.name + ' (ID: ' + guild.id + ')');",
    "  getGuildConfig(guild.id, guild.name);",
    "  await syncWithDashboard(true, { add: String(guild.id), replace: false });",
    "});",
    "",
    "client.on('guildDelete', async (guild) => {",
    "  console.log('🗑️ [Event] Bot usunięty z serwera: ' + guild.name + ' (ID: ' + guild.id + ')');",
    "  await syncWithDashboard(true, { remove: String(guild.id), replace: false });",
    "});",
    "",
    "// Obsługa komend slash",
    "client.on('interactionCreate', async (interaction) => {",
    "  if (interaction.isButton()) {",
    "    if (interaction.customId === 'verify_welcome_btn' || interaction.customId === 'verify_user_btn') {",
    "      await interaction.reply({ content: '✅ Dziękujemy! Twoje konto zostało pomyślnie zweryfikowane na serwerze.', ephemeral: true });",
    "      return;",
    "    }",
    "    await interaction.reply({ content: '👌 Kliknięto przycisk bota: `' + interaction.customId + '`', ephemeral: true });",
    "    return;",
    "  }",
    "",
    "  if (!interaction.isChatInputCommand()) return;",
    "  const { commandName, guild } = interaction;",
    "  const config = guild ? getGuildConfig(guild.id, guild.name) : null;",
    "",
    "  if (commandName === 'pomoc') {",
    "    const embed = new EmbedBuilder()",
    "      .setTitle('🤖 KitekBot v5.0.0 - Panel Pomocy')",
    "      .setDescription('Zarządzaj potężnym modułem powitań w **Panelu Web Dashboard**!')",
    "      .addFields(",
    "        { name: '🌐 Web Dashboard', value: process.env.DASHBOARD_URL || '" + dashboardUrl + "', inline: false },",
    "        { name: '📋 Komendy', value: '`/pomoc` - Informacje o bocie\\n`/ping` - Sprawdza opóźnienie\\n`/stan` - Stan serwera i kanału powitań', inline: false }",
    "      )",
    "      .setColor(config && config.embedColor ? config.embedColor : '#5865F2')",
    "      .setFooter({ text: 'KitekBot v5.0.0 • Message.style Welcome System' });",
    "    await interaction.reply({ embeds: [embed] });",
    "  } else if (commandName === 'ping') {",
    "    await interaction.reply({ content: '🏓 Pong! Opóźnienie bota wynosi: **' + client.ws.ping + 'ms**', ephemeral: true });",
    "  } else if (commandName === 'stan') {",
    "    const membersCount = guild ? guild.memberCount : 0;",
    "    const guildName = guild ? guild.name : 'Nieznany serwer';",
    "    const channelId = config && config.welcome ? config.welcome.channelId : null;",
    "    await interaction.reply({",
    "      content: '📊 **Stan serwera:** ' + guildName + '\\n• Liczba członków: **' + membersCount + '**\\n• Moduł powitań: **' + (config && config.welcome && config.welcome.enabled ? 'WŁĄCZONY' : 'WYŁĄCZONY') + '**\\n• Kanał powitań: ' + (channelId ? '<#' + channelId + '>' : '`Brak wybranego kanału`'),",
    "      ephemeral: true",
    "    });",
    "  }",
    "});",
    "",
    "// Event: Nowy członek na serwerze (Wysyłanie powitania)",
    "client.on('guildMemberAdd', async (member) => {",
    "  const config = getGuildConfig(member.guild.id, member.guild.name);",
    "  if (config.welcome && config.welcome.enabled && config.welcome.channelId) {",
    "    const channel = member.guild.channels.cache.get(config.welcome.channelId);",
    "    if (channel && channel.isTextBased()) {",
    "      try {",
    "        const payload = buildWelcomePayload(member.guild, member, config);",
    "        await channel.send(payload);",
    "      } catch (err) {",
    "        console.error('⚠️ Błąd podczas wysyłania powitania:', err.message);",
    "      }",
    "    }",
    "  }",
    "});",
    "",
    "// --- 2. SERWER EXPRESS REST / HTTPS API v5.0.0 ---",
    "const app = express();",
    "const API_PORT = process.env.PORT || 3001;",
    "",
    "const checkAuth = (req, res, next) => {",
    "  const secret = (process.env.BOT_API_SECRET || '').trim();",
    "  if (!secret) return next();",
    "  const authHeader = req.headers['authorization'] || '';",
    "  const token = authHeader.replace(/^Bearer\\s+/i, '').trim() || req.headers['x-bot-token'] || req.query.token;",
    "  if (token !== secret) {",
    "    return res.status(401).json({ success: false, error: 'Brak autoryzacji: nieprawidłowy token REST API bota' });",
    "  }",
    "  next();",
    "};",
    "",
    "app.use(cors());",
    "app.use(express.json());",
    "",
    "app.get('/api/health', (req, res) => {",
    "  res.json({",
    "    status: 'ok',",
    "    botOnline: client.isReady(),",
    "    botTag: client.user ? client.user.tag : null,",
    "    guildsCount: client.guilds.cache.size,",
    "    version: '5.0.0'",
    "  });",
    "});",
    "",
    "app.get('/api/status', (req, res) => {",
    "  const guilds = client.guilds.cache.map(g => ({",
    "    id: g.id,",
    "    name: g.name,",
    "    icon: g.iconURL ? g.iconURL({ size: 128 }) : null,",
    "    memberCount: g.memberCount",
    "  }));",
    "  res.json({",
    "    success: true,",
    "    status: client.isReady() ? 'online' : 'connecting',",
    "    botTag: client.user ? client.user.tag : 'KitekBot',",
    "    botId: client.user ? client.user.id : null,",
    "    botAvatar: client.user ? client.user.displayAvatarURL() : null,",
    "    ping: client.ws ? client.ws.ping : null,",
    "    uptimeSeconds: Math.floor(process.uptime()),",
    "    guildsCount: client.guilds.cache.size,",
    "    guildIds: guilds.map(g => g.id),",
    "    guilds: guilds,",
    "    version: '5.0.0',",
    "    memoryMb: Math.round(process.memoryUsage().heapUsed / 1024 / 1024),",
    "    timestamp: Date.now()",
    "  });",
    "});",
    "",
    "app.get('/api/bot/guilds', (req, res) => {",
    "  const guilds = client.guilds.cache.map(g => ({",
    "    id: g.id,",
    "    name: g.name,",
    "    icon: g.iconURL ? g.iconURL({ size: 128 }) : null,",
    "    memberCount: g.memberCount",
    "  }));",
    "  res.json({",
    "    success: true,",
    "    guildIds: guilds.map(g => g.id),",
    "    guilds: guilds,",
    "    count: guilds.length,",
    "    timestamp: Date.now()",
    "  });",
    "});",
    "",
    "app.get('/api/bot/guilds/:id/channels', checkAuth, (req, res) => {",
    "  const guild = client.guilds.cache.get(req.params.id);",
    "  if (!guild) return res.status(404).json({ success: false, error: 'Bot nie jest na tym serwerze' });",
    "  try {",
    "    const channels = guild.channels.cache",
    "      .filter(c => c.isTextBased())",
    "      .map(c => ({ id: c.id, name: c.name, type: c.type }));",
    "    res.json({ success: true, channels });",
    "  } catch (err) {",
    "    res.status(500).json({ success: false, error: err.message });",
    "  }",
    "});",
    "",
    "// Endpoint wysyłania testowego powitania z panelu",
    "app.post('/api/bot/guilds/:id/test-welcome', checkAuth, async (req, res) => {",
    "  const guild = client.guilds.cache.get(req.params.id);",
    "  if (!guild) return res.status(404).json({ success: false, error: 'Bot nie znajduje się na tym serwerze' });",
    "  const config = req.body || getGuildConfig(guild.id, guild.name);",
    "  const targetChannelId = config.welcome ? config.welcome.channelId : null;",
    "  if (!targetChannelId) {",
    "    return res.status(400).json({ success: false, error: 'Wybierz najpierw kanał docelowy w panelu powitań!' });",
    "  }",
    "  const channel = guild.channels.cache.get(targetChannelId);",
    "  if (!channel || !channel.isTextBased()) {",
    "    return res.status(400).json({ success: false, error: 'Wybrany kanał nie istnieje na serwerze lub nie jest kanałem tekstowym' });",
    "  }",
    "  try {",
    "    const mockMember = guild.members.me || { id: client.user.id, user: client.user, guild };",
    "    const payload = buildWelcomePayload(guild, mockMember, config);",
    "    await channel.send(payload);",
    "    res.json({ success: true, message: 'Pomyślnie wysłano wiadomość testową na kanał #' + channel.name + '!' });",
    "  } catch (err) {",
    "    res.status(500).json({ success: false, error: 'Błąd Discord API: ' + err.message });",
    "  }",
    "});",
    "",
    "app.get('/api/guilds/:id', (req, res) => {",
    "  const guildId = req.params.id;",
    "  const guild = client.guilds.cache.get(guildId);",
    "  const config = getGuildConfig(guildId, guild ? guild.name : '');",
    "  res.json({",
    "    success: true,",
    "    guildName: guild ? guild.name : config.guildName,",
    "    botInGuild: !!guild,",
    "    config: config",
    "  });",
    "});",
    "",
    "app.post('/api/guilds/:id', checkAuth, (req, res) => {",
    "  const guildId = req.params.id;",
    "  const updatedConfig = req.body;",
    "  if (!updatedConfig) {",
    "    return res.status(400).json({ error: 'Brak danych konfiguracyjnych' });",
    "  }",
    "  const saved = saveGuildConfig(guildId, updatedConfig);",
    "  res.json({",
    "    success: true,",
    "    message: 'Konfiguracja zapisana pomyślnie w pliku JSON!',",
    "    config: saved",
    "  });",
    "});",
    "",
    "app.get('/api/guilds', (req, res) => {",
    "  const all = getAllConfigs();",
    "  res.json({ success: true, configs: all });",
    "});",
    "",
    "app.listen(API_PORT, () => {",
    "  console.log('🌐 [REST API] KitekBot v5.0.0 nasłuchuje na porcie ' + API_PORT);",
    "  console.log('🔗 [REST API] Endpointy: /api/status | /api/bot/guilds | /api/guilds/:id | /api/bot/guilds/:id/test-welcome');",
    "});",
    "",
    "const tokenToLogin = (process.env.DISCORD_TOKEN || '')",
    "  .replace(/[\"']/g, '')",
    "  .replace(/^Bot\\s+/i, '')",
    "  .trim();",
    "",
    "if (tokenToLogin && tokenToLogin !== 'TWOJ_DISCORD_BOT_TOKEN_TUTAJ') {",
    "  console.log('🔑 Logowanie do Discord Gateway...');",
    "  client.login(tokenToLogin).catch(err => {",
    "    console.error('\\n❌ [BŁĄD LOGOWANIA DISCORD]');",
    "    console.error('Wskazany token jest nieprawidłowy lub wygasł:', err.message);",
    "    console.error('👉 Wejdź na https://discord.com/developers/applications, wybierz bota, kliknij Bot -> Reset Token i wklej nowy token do .env\\n');",
    "  });",
    "} else {",
    "  console.log('\\n⚠️ [KROK KONFIGURACYJNY]');",
    "  console.log('1. Otwórz plik .env na hostingu');",
    "  console.log('2. Wklej swój DISCORD_TOKEN z portalu Discord Developers');",
    "  console.log('3. Zrestartuj serwer w panelu Pterodactyl, aby bot połączył się z Discordem!\\n');",
    "}"
  ].join("\n");
  zip.file("index.js", indexJs);

  // 6. README.md
  const readmeContent = [
    '# 🤖 KitekBot v5.0.0 - Discord Bot z Zaawansowanym Modułem Powitań (Message.style)',
    '',
    'Kompletny bot Discord w Node.js zintegrowany bezpośrednio z panelem Web Dashboard. Skupiony w 100% na najwyższej jakości powitaniach dla nowych użytkowników!',
    '',
    '## ✨ Najważniejsze funkcje v5.0.0:',
    '- 🎨 **Edytor wiadomości i kart Embed** w stylu [message.style](https://message.style/app/editor)',
    '- 🌈 Pełna paleta kolorów Discord oraz dowolne kody HEX',
    '- 📝 Pasek zmiennych: `{user}`, `{user.mention}`, `{user.name}`, `{server.name}`, `{memberCount}`, `{user.id}`',
    '- 📌 Dynamiczne pola (Fields) z opcją układu inline',
    '- 🖼️ Miniaturki (thumbnail) oraz duże banery (image)',
    '- 🔘 Przyciski interaktywne Discord (Action Row Buttons: Primary, Secondary, Success, Danger, Link)',
    '- 🚀 Natychmiastowe testowanie wiadomości na kanale Discord (`/test-welcome`)',
    '',
    '## 🚀 Jak uruchomić na hostingu (Pterodactyl, VPS, Render, Bot-Hosting.net):',
    '',
    '1. **Wypakuj pliki** bota do katalogu głównego serwera.',
    '2. Otwórz plik `.env` i wklej swój **DISCORD_TOKEN**:',
    '   ```env',
    '   DISCORD_TOKEN=twoj_prawdziwy_token_z_discord_developers',
    '   ```',
    '3. Uruchom serwer na hostingu (zależności zainstalują się automatycznie!).',
    '4. W panelu Dashboard konfiguruj powitania z podglądem na żywo i zapisuj jednym kliknięciem!',
    '',
    '## 📡 Endpointy REST API:',
    '- `GET /api/status` - Szczegółowy stan bota, opóźnienie ping, pamięć RAM, lista serwerów',
    '- `GET /api/bot/guilds` - Lista serwerów bota na żywo z Discord Gateway',
    '- `GET /api/bot/guilds/:id/channels` - Kanały tekstowe serwera',
    '- `POST /api/bot/guilds/:id/test-welcome` - Natychmiastowe wysłanie testowego powitania',
    '- `GET /api/guilds/:id` & `POST /api/guilds/:id` - Odczyt i zapis konfiguracji w plikach JSON',
    '',
    '## 📁 Struktura plików:',
    '- `index.js` - Główny plik bota v5.0.0, silnik powitań oraz serwer REST API',
    '- `.env` - Zmienne środowiskowe, token bota oraz adres Dashboardu',
    '- `Serwery/` - Folder z plikami JSON dla każdego serwera (np. `123456789.json`)',
    '- `utils/configManager.js` - Narzędzie do automatycznego zapisu i odczytu plików JSON',
    ''
  ].join('\n');
  zip.file("README.md", readmeContent);

  return zip;
}
